[workspace]
resolver = "2"
members = [
    "crates/pm-proto",
    "crates/pm-crypto",
    "crates/pm-store",
    "crates/pm-transport",
    "crates/pm-node",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/srfrog1970/yougle"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "2"
